app = "rushago-api"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "15000"

[[services]]
  internal_port = 15000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
